package com.example.pkl_v1.model

class ModelDataset(
    val AccXAvg: Double,
    val AccXStd: Double,
    val AccXMin: Double,
    val AccXMax: Double,
    val AccXMedian: Double,
    val AccXSkewness: Double,
    val AccXKurtosis: Double,
    val AccXVariance: Double,
    val AccXPercentil: Double,
    val AccXIq: Double,

    val AccYAvg: Double,
    val AccYStd: Double,
    val AccYMin: Double,
    val AccYMax: Double,
    val AccYMedian: Double,
    val AccYSkewness: Double,
    val AccYKurtosis: Double,
    val AccYVariance: Double,
    val AccYPercentil: Double,
    val AccYIq: Double,

    val AccZAvg: Double,
    val AccZStd: Double,
    val AccZMin: Double,
    val AccZMax: Double,
    val AccZMedian: Double,
    val AccZSkewness: Double,
    val AccZKurtosis: Double,
    val AccZVariance: Double,
    val AccZPercentil: Double,
    val AccZIq: Double,

    val GyroXAvg: Double,
    val GyroXStd: Double,
    val GyroXMin: Double,
    val GyroXMax: Double,
    val GyroXMedian: Double,
    val GyroXSkewness: Double,
    val GyroXKurtosis: Double,
    val GyroXVariance: Double,
    val GyroXPercentil: Double,
    val GyroXIq: Double,

    val GyroYAvg: Double,
    val GyroYStd: Double,
    val GyroYMin: Double,
    val GyroYMax: Double,
    val GyroYMedian: Double,
    val GyroYSkewness: Double,
    val GyroYKurtosis: Double,
    val GyroYVariance: Double,
    val GyroYPercentil: Double,
    val GyroYIq: Double,

    val GyroZAvg: Double,
    val GyroZStd: Double,
    val GyroZMin: Double,
    val GyroZMax: Double,
    val GyroZMedian: Double,
    val GyroZSkewness: Double,
    val GyroZKurtosis: Double,
    val GyroZVariance: Double,
    val GyroZPercentil: Double,
    val GyroZIq: Double,
    val label: String

) {
}